interactive_fiction/book/urls.py
from django.urls import path

from .views import BookView
from .views import IndexView
from .views import PageView
from .views import TakeView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("book/<int:book_id>", BookView.as_view(), name="book"),
    path("book/<int:book_id>/page/<int:page_id>", PageView.as_view(), name="page"),
    path("book/<int:book_id>/page/<int:page_id>/take/<int:item_id>", TakeView.as_view(), name="take"),
]

interactive_fiction/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("ifbook.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

interactive_fiction/ifbook/urls.py
from django.urls import path

from .views import BookView
from .views import IndexView
from .views import PageView
from .views import RegistrationView
from .views import TakeView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path("book/<int:book_id>", BookView.as_view(), name="book"),
    path("book/<int:book_id>/page/<int:page_id>", PageView.as_view(), name="page"),
    path("book/<int:book_id>/page/<int:page_id>/take/<int:item_id>", TakeView.as_view(), name="take"),
]

interactive_fiction/book/models.py
from __future__ import annotations

from django.db import models


class Book(models.Model):
    title = models.TextField(name="title", unique=True)  # Заголовок книги
    first_page = models.ForeignKey("BookPage",
                                   null=True,
                                   on_delete=models.SET_NULL,
                                   related_name="first_page")  # Ссылка на первую страницу книги
    cover_art = models.ImageField(upload_to='books_cover', null=True)

    def __str__(self):
        # Строковое представление модели Book
        return f"{self.title} ({self.id})"


class BookPage(models.Model):
    title = models.TextField(name="title")  # Заголовок страницы
    book = models.ForeignKey(Book, on_delete=models.CASCADE)  # Ссылка на книгу, к которой относится страница
    body = models.TextField(name="body")  # Содержимое страницы

    def __str__(self):
        # Строковое представление модели BookPage
        return f"{self.title} ({self.id})"


class PageLink(models.Model):
    name = models.TextField()  # Название ссылки
    from_page = models.ForeignKey(BookPage, on_delete=models.CASCADE)  # Ссылка на исходную страницу
    to_page = models.ForeignKey(BookPage,
                                related_name="to_page",
                                on_delete=models.CASCADE)  # Ссылка на целевую страницу

    def __str__(self):
        # Строковое представление модели PageLink
        return f"{self.from_page.title} -> {self.to_page.title} ({self.id})"

    class Meta:
        # Уникальность комбинации исходной и целевой страницы для модели PageLink
        unique_together = ["from_page", "to_page"]

interactive_fiction/book/models/book.py
from __future__ import annotations

from django.contrib.auth.models import User
from django.db import models

from .item import Item


class Book(models.Model):
    title = models.TextField(name="title", unique=True)  # Заголовок книги
    first_page = models.ForeignKey("BookPage",
                                   null=True,
                                   on_delete=models.SET_NULL,
                                   related_name="first_page")  # Ссылка на первую страницу книги
    cover_art = models.ImageField(upload_to='books_cover', null=True)

    def __str__(self):
        # Строковое представление модели Book
        return f"{self.title} ({self.id})"


class BookPage(models.Model):
    title = models.TextField(name="title")  # Заголовок страницы
    book = models.ForeignKey(Book, on_delete=models.CASCADE)  # Ссылка на книгу, к которой относится страница
    body = models.TextField(name="body")  # Содержимое страницы
    items = models.ManyToManyField(Item, blank=True)

    def __str__(self):
        # Строковое представление модели BookPage
        return f"{self.title} ({self.id})"


class BookProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)  # Ссылка на книгу, к которой относится страница
    book_page = models.ForeignKey(BookPage, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item, blank=True)

    class Meta:
        unique_together = ['user', 'book']

    @classmethod
    def start_reading(cls, user, book):
        progress = BookProgress(user=user, book=book, book_page=book.first_page)
        progress.save()
        return progress

    @classmethod
    def reading_progress(self, user, book):
        try:
            progress = BookProgress.objects.get(book=book, user=user)
        except BookProgress.DoesNotExist:
            return None

        return progress

    def save_progress(self, page_id):
        self.book_page = page_id
        self.save()

interactive_fiction/book/models/item.py
from __future__ import annotations

from django.db import models


class Item(models.Model):
    name = models.TextField()

    def __str__(self):
        return f"{self.name}"

interactive_fiction/book/models/page.py
from __future__ import annotations

from django.db import models

from .book import BookPage
from .item import Item


class PageLink(models.Model):
    name = models.TextField()  # Название ссылки
    from_page = models.ForeignKey(BookPage,
                                  on_delete=models.CASCADE)  # Ссылка на исходную страницу
    to_page = models.ForeignKey(BookPage,
                                related_name="to_page",
                                on_delete=models.CASCADE)  # Ссылка на целевую страницу

    items = models.ManyToManyField(Item, blank=True)  # требуемые предметы для перехода по ссылке

    class Meta:
        # Уникальность комбинации исходной и целевой страницы для модели PageLink
        unique_together = ["from_page", "to_page"]

    def __str__(self):
        # Строковое представление модели PageLink
        return f"{self.from_page.title} -> {self.to_page.title} ({self.id})"

    def has_all_required(self, required_progress_items):
        # проверяем все ли вещи у нас есть для того, чтобы пройти по ссылке
        return all(item in required_progress_items for item in self.items.all())

interactive_fiction/ifbook/models/book.py
from django.db import models

from .page import BookPage

FIRST_PAGE_TITLE = "Первая страница"
FIRST_PAGE_BODY = "Это автоматически созданная первая страница твоей книги. " \
                  "Ты можешь поменять название и содержание в панели администратора"


class Book(models.Model):
    title = models.TextField(name="title", unique=True)
    description = models.TextField(name='description', null=True)
    first_page = models.ForeignKey("BookPage",
                                   null=True,
                                   blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="first_page")
    cover_art = models.ImageField(upload_to='books_cover', null=True)

    def __str__(self):
        return f"{self.title} ({self.id})"

    def save(self, *args, **kwargs):
        if not self.first_page:
            first_page = BookPage.objects.create(title=FIRST_PAGE_TITLE, body=FIRST_PAGE_BODY)
            self.first_page = first_page

            super().save(*args, **kwargs)  # Сохраняем Book, чтобы получить ID

            # Устанавливаем связь между книгой и первой страницей
            first_page.book = self
            first_page.save()
        else:
            super().save(*args, **kwargs)

interactive_fiction/ifbook/models/item.py
from django.db import models


class BookItem(models.Model):
    name = models.TextField()

    def __str__(self):
        return f"{self.name}"

interactive_fiction/ifbook/models/page.py
from django.db import models


class BookPage(models.Model):
    title = models.TextField(name="title")
    book = models.ForeignKey("Book", null=True, blank=True, on_delete=models.CASCADE)
    body = models.TextField(name="body")
    items = models.ManyToManyField("BookItem", blank=True)

    def __str__(self):
        return f"{self.title} ({self.id})"

interactive_fiction/ifbook/models/page_link.py
from django.db import models

from .item import BookItem
from .page import BookPage


class PageLink(models.Model):
    name = models.TextField()  # Название ссылки
    from_page = models.ForeignKey(BookPage,
                                  on_delete=models.CASCADE)  # Ссылка на исходную страницу
    to_page = models.ForeignKey(BookPage,
                                related_name="to_page",
                                on_delete=models.CASCADE)  # Ссылка на целевую страницу

    items = models.ManyToManyField(BookItem, blank=True)  # требуемые предметы для перехода по ссылке

    class Meta:
        # Уникальность комбинации исходной и целевой страницы для модели PageLink
        unique_together = ["from_page", "to_page"]

    def __str__(self):
        # Строковое представление модели PageLink
        return f"{self.from_page.title} -> {self.to_page.title} ({self.id})"

    def has_all_required(self, required_progress_items):
        # проверяем все ли вещи у нас есть для того, чтобы пройти по ссылке
        return all(item in required_progress_items for item in self.items.all())

interactive_fiction/ifbook/models/progress.py
from django.contrib.auth.models import User
from django.db import models

from .book import Book
from .item import BookItem
from .page import BookPage


class BookProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    book_page = models.ForeignKey(BookPage, on_delete=models.CASCADE, null=True, blank=True)
    items = models.ManyToManyField(BookItem, blank=True)

    class Meta:
        unique_together = ['user', 'book']

    @classmethod
    def start_reading(cls, user, book):
        first_page = book.first_page
        progress = BookProgress(user=user, book=book, book_page=first_page)
        progress.save()
        return progress

    @classmethod
    def reading_progress(cls, user, book):
        try:
            progress = BookProgress.objects.get(book=book, user=user)
        except BookProgress.DoesNotExist:
            return None

        return progress

    def save_progress(self, page_id):
        self.book_page = page_id
        self.save()

interactive_fiction/ifbook/forms/registration.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    error_css_class = 'error'

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

interactive_fiction/book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View

from .models.book import Book
from .models.book import BookPage
from .models.book import BookProgress
from .models.item import Item


class IndexView(View):
    def get(self, request):
        '''Отрисовка главной страницы'''
        return render(request, "book_index.html", context={"books": Book.objects.all()})


class BookView(LoginRequiredMixin, View):
    def get(self, request, book_id):
        '''Отрисовка книги'''
        b = get_object_or_404(Book, id=book_id)
        if not b.first_page:
            return render(request, "book.html", context={"book": b})

        progress = BookProgress.reading_progress(user=request.user, book=b)
        if progress is None:
            progress = BookProgress.start_reading(user=request.user, book=b)

        return redirect(reverse("page", kwargs={"book_id": b.id, "page_id": progress.book_page.id}))


class PageView(LoginRequiredMixin, View):
    def get(self, request, book_id, page_id):
        '''Отрисовка страницы'''
        progress = BookProgress.reading_progress(user=request.user, book=book_id)
        if progress is None:
            return redirect(reverse("book", kwargs={"book_id": book_id}))

        page = get_object_or_404(BookPage, book__id=book_id, id=page_id)
        progress.save_progress(page_id=page)

        links = [
            (link, link.has_all_required(list(progress.items.all()))) for link in page.pagelink_set.all()
        ]
        print(links)

        return render(request,
                      "page.html",
                      context={"page": get_object_or_404(BookPage, book__id=book_id, id=page_id),
                               "items": progress.items.all(),
                               "page_items": page.items.exclude(id__in=progress.items.only('id')),
                               "links": links
                               })


class TakeView(LoginRequiredMixin, View):
    def get(self, request, book_id, page_id, item_id):
        progress = BookProgress.reading_progress(user=request.user, book=book_id)
        if progress is None:
            return redirect(reverse("book", kwargs={"book_id": book_id}))

        item = get_object_or_404(Item, id=item_id)
        progress.items.add(item)

        return redirect(reverse('page', kwargs={'book_id': book_id,
                                                'page_id': page_id}))

interactive_fiction/ifbook/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import FormView
from django.views.generic import ListView

from .forms.registration import RegistrationForm
from .models.book import Book
from .models.item import BookItem
from .models.page import BookPage
from .models.progress import BookProgress


class RegistrationView(FormView):
    template_name = 'registration/registration.html'
    form_class = RegistrationForm
    success_url = '/'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class IndexView(ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'book_index.html'


class BookView(LoginRequiredMixin, View):
    def get(self, request, book_id):
        '''Отрисовка книги'''

        book = get_object_or_404(Book, id=book_id)
        if not book.first_page:
            return render(request, "book.html", context={"book": book})

        progress = BookProgress.reading_progress(user=request.user, book=book)
        if progress is None:
            progress = BookProgress.start_reading(user=request.user, book=book)

        return redirect(reverse("page", kwargs={"book_id": book.id,
                                                "page_id": progress.book_page.id}))


class PageView(LoginRequiredMixin, View):
    def get(self, request, book_id, page_id):
        '''Отрисовка страницы'''
        progress = BookProgress.reading_progress(user=request.user, book=book_id)
        if progress is None:
            return redirect(reverse("book", kwargs={"book_id": book_id}))

        page = get_object_or_404(BookPage, book__id=book_id, id=page_id)
        progress.save_progress(page_id=page)

        links = [
            (link, link.has_all_required(list(progress.items.all()))) for link in page.pagelink_set.all()
        ]

        return render(request,
                      "page.html",
                      context={"page": get_object_or_404(BookPage, book__id=book_id, id=page_id),
                               "items": progress.items.all(),
                               "page_items": page.items.exclude(id__in=progress.items.only('id')),
                               "links": links
                               })


class TakeView(LoginRequiredMixin, View):
    def get(self, request, book_id, page_id, item_id):
        progress = BookProgress.reading_progress(user=request.user, book=book_id)
        if progress is None:
            return redirect(reverse("book", kwargs={"book_id": book_id}))

        item = get_object_or_404(BookItem, id=item_id)
        progress.items.add(item)

        return redirect(reverse('page', kwargs={'book_id': book_id,
                                                'page_id': page_id}))

interactive_fiction/ifbook/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
    <!-- Подключение Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
<!-- Шапка навигации -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Интерактивные Книги</a>
        <a class="navbar-brand disabled" >{{ page.book.title }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                     <a class="nav-link disabled">{{ user.username }}</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Вход</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<main class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>

<!-- Подключение скриптов Bootstrap 5 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

interactive_fiction/ifbook/templates/book.html
<!-- templates/login.html -->
{% extends 'base.html' %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h1 class="card-title">{{ book.title }}</h1>
    </div>
    <div class="card-body">
        <ul class="list-group">
            {% for page in book.bookpage_set.all %}
            <li class="list-group-item"><a href="{% url 'page' book.id page.id %}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

interactive_fiction/ifbook/templates/book_index.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container text-center">
    {% if not user.is_authenticated %}
        <script>
        Swal.fire({
            icon: 'info',
            title: 'Вы не авторизированы!',
            text: 'Вы можете видеть список доступных книг, но не играть в них',
            confirmButtonText: 'Войти',
            showCancelButton: true,
            cancelButtonText: 'Отмена',
            cancelButtonColor: '#d33',
            allowOutsideClick: false,
            allowEscapeKey: false,
            showDenyButton: true,
            denyButtonText: 'Регистрация',
            denyButtonColor: '#00A36C',
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = "{% url 'login' %}";
            } else if (result.isDenied) {
                window.location.href = "{% url 'registration' %}";
            }
        });


        </script>

    {% else %}

        {% if not books %}
        <h3>На данный момент нет доступных книг</h3>
        {% else %}
        <h3>На данный момент кол-во доступных книг: {{ books|length }}</h3>
        {% endif %}
    {% endif %}

    <div id="bookCarousel" class="carousel slide" data-bs-ride="carousel">
        <!-- Индикаторы слайдов -->
        <ol class="carousel-indicators">
            {% for book in books %}
            <li data-bs-target="#bookCarousel" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
            {% endfor %}
        </ol>

        <!-- Содержимое слайдов -->
        <div class="carousel-inner">
            {% for book in books %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <a href="book/{{ book.id }}">
                    {% if book.cover_art %}
                    <img src="{{ book.cover_art.url }}" class="d-block" style="width: 800px; height: 800px; object-fit: cover;">

                    {% endif %}
                    <div class="carousel-caption">
                        <h5>{{ book.title }}</h5>
                        <p>{{ book.description }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>

        <!-- Кнопки переключения слайдов -->
        <a class="carousel-control-prev" href="#bookCarousel" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </a>
        <a class="carousel-control-next" href="#bookCarousel" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </a>
    </div>

</div>
{% endblock %}

interactive_fiction/ifbook/templates/page.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}{{ page.book.title }} {{ page.title }}{% endblock %}

{% block content %}
<div class="container">
    <h2 class="text-center"> {{ page.title }}</h2>
    <div class="card">
        <div class="card-body text-center">
            {{ page.body }}
            {% if page_items %}
            <hr>
            <h4>Вы видите:</h4>
            {% for item in page_items %}
            <li class="list-group-item text-center">
                {{ item.name }} <a href="{% url 'take' page.book.id page.id item.id %}"
                                   onclick="showSuccessMessage(event, '{{ item.name }}')"> взять </a>
            </li>
            {% endfor %}
            {% endif %}
            {% if page.pagelink_set.all %}
            <hr>
            <h4>Куда податься?</h4>
            <ul class="list-group">
                {% for link, passable in links %}
                <li class="list-group-item text-center">
                    {% if passable %}
                    <a href="{% url 'page' page.book.id link.to_page.id %}">
                        {{ link.name }}
                    </a>
                    {% else %}
                    {{ link.name }}
                    {% endif %}
                </li>
                {% endfor %}
                {% endif %}
            </ul>

        </div>

    </div>

</div>

<div class="text-center" style="position: absolute; left: 0;">
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                data-bs-toggle="dropdown" aria-expanded="false">
            Инвентарь
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% for item in items %}
            <li><a class="dropdown-item" href="#">{{ item.name }}</a></li>
            {% endfor %}
        </ul>
    </div>

</div>

<script>
    function showSuccessMessage(event, itemName) {
        event.preventDefault(); // Отменяем стандартное поведение ссылки

        Swal.fire({
            icon: 'success',
            title: 'Вы взяли ' + itemName,
            showConfirmButton: false,
            timer: 1500
        }).then(() => {
            // После закрытия окна, выполняем переход по ссылке
            window.location.href = event.target.href;
        });
    }

</script>

{% endblock %}